### ISSUE TITLE
Build requirements

### ISSUE THREAD

**Issue by colms** [munificent/journal#2]
I've been playing with the idea of starting a blog and yours was one of the templates I tried out. I had some problems building your blog with Jekyll. Jekyll was producing empty HTML files. I tracked the error to [here](https://github.com/jekyll/jekyll/issues/1181).

I discovered that to build your blog, I had to have the following versions of software due to incompatibility with pygments:
- Ruby 2.0.0
- Python 2.7.6
- Pygments 0.5.0

I had to uninstall Python 3 and install 2.7.6, and uninstall Pygments 0.5.4 and install 0.5.0. It also complained about missing the magpie lexer. These problems can of course be fixed by deleting the posts that contain code. I was starting from scratch so deleting all posts makes sense for me. Nevertheless, I thought I'd just create an issue in case some other chap tries to build the blog.

**Comment by munificent** [comment]
Heh, I forgot all about this bug. But I guess it's "fixed" now because I've rewritten my entire build engine from scratch in Dart. It's entirely self-contained now.

**Comment by imflash217** [comment]
Hi @munificent Thank you for great resources. I am building my own journal using inspiration from yours. However, I am not able to host it in Github Pages. How are you hosting it?

**Comment by munificent** [comment]
> However, I am not able to host it in Github Pages. How are you hosting it?

I have a basic shared web host. I'm using HostPapa, but any basic web host should work.

**Comment by imflash217** [comment]
Thank you Bob @munificent . I got it deployed using AWS Amplify.

**Comment by imflash217** [comment]
Hi @munificent, I am trying to render `LaTeX` equations using `$....$` block. However, it does not get rendered. Anyone have any idea on how to achieve it. Thanks

**Comment by munificent** [comment]
I don't have any LaTeX support at all.

To set expectations here: I wrote this for my blog, but I don't have any intention of supporting this as a general-purpose site generator. Users are welcome to fork the code, but I'm not trying to turn this into anything like a product.
