### ISSUE TITLE
The blog feed contains undefined entities and does not validate

### ISSUE THREAD

**Issue by auouymous** [munificent/journal#20]
The `&ldquo;` and `&rdquo;` entities are undefined in firefox, rss2email (a python based reader) and the w3 feed validator https://validator.w3.org/feed/check.cgi?url=http%3A%2F%2Fjournal.stuffwithstuff.com%2Fatom.xml.

**Comment by KopfKrieg** [comment]
It seems that `&ldquo;` could be replaced with `&#8220;`, and `&rdquo;` with `&#8221;` (see [here](https://www.w3.org/TR/REC-html40/sgml/entities.html))

However, I haven't tested that.

**Comment by munificent** [comment]
Thanks for the heads up. I think it should be fixed now, but let me know if you see any problems.
