### ISSUE TITLE
wrong date in README

### ISSUE THREAD

**Issue by CaptainChloride** [munificent/journal#4]
Hey

looks like your README file says 2008-2011. I know it must be so glorious at Google that you forget time entirely, but pls update. :smile:

**Comment by munificent** [comment]
Haha, yes! Time flies when you're having fun!

**Comment by CaptainChloride** [comment]
Oh by the way, I sent you an email on robert at stuffwithstuff I'd really
appreciate if you could reply. Thanks :)
